# Espanso configuration file for greek letters

name: greek-letters-full
parent: default



matches:

    ## Letter shorthand
    # :gA: ⇒ A
    - trigger: ":gA:"
      replace: "Α"
      
    # :ga: ⇒ α
    - trigger: ":ga:"
      replace: "α"

    # :gB: ⇒ Β
    - trigger: ":gB:"
      replace: "Β"
    
    # :gb: ⇒ β
    - trigger: ":gb:"
      replace: "β"

    # :gD: ⇒ Δ
    - trigger: ":gD:"
      replace: "Δ"

    # :gd: ⇒ δ
    - trigger: ":gd:"
      replace: "δ"
      
    # :gE: ⇒ Ε
    - trigger: ":gE:"
      replace: "Ε"
      
    # :ge: ⇒ ε
    - trigger: ":ge:"
      replace: "ε"
      
    # :gF: ⇒ Φ
    - trigger: ":gF:"
      replace: "Φ"
    
    # :gf: ⇒ φ
    - trigger: ":gf:"
      replace: "φ"
    
    # :gG: ⇒ Γ
    - trigger: ":gG:"
      replace: "Γ"
      
    # :gg: ⇒ γ
    - trigger: ":gg:"
      replace: "γ"
      
    # :gH: ⇒ Η
    - trigger: ":gH:"
      replace: "Η"
    
    # :gh: ⇒ η
    - trigger: ":gh:"
      replace: "η"
      
    # :gI: ⇒ Ι
    - trigger: ":gI:"
      replace: "Ι"
    
    # :gi: ⇒ ι
    - trigger: ":gi:"
      replace: "ι"
      
    # :gJ: ⇒ Θ
    - trigger: ":gJ:"
      replace: "Θ"
    
    # :gj: ⇒ θ
    - trigger: ":gj:"
      replace: "θ"

    # :gK: ⇒ Κ
    - trigger: ":gK:"
      replace: "Κ"
      
    # :gk: ⇒ κ
    - trigger: ":gk:"
      replace: "κ"
      
    # :gL: ⇒ Λ
    - trigger: ":gL:"
      replace: "Λ"
      
    # :gl: ⇒ λ
    - trigger: ":gl:"
      replace: "λ" 
      
    # :gM: ⇒ Μ
    - trigger: ":gM:"
      replace: "Μ"
    
    # :gm: ⇒ μ
    - trigger: ":gm:"
      replace: "μ"
    
    # :gN: ⇒ Ν
    - trigger: ":gN:"
      replace: "Ν"
      
    # :gn: ⇒ ν
    - trigger: ":gn:"
      replace: "ν"
    
    # :gO: ⇒ Ο
    - trigger: ":gO:"
      replace: "Ο"
      
    # :go: ⇒ ο
    - trigger: ":go:"
      replace: "ο"
      
    # :gP: ⇒ Π
    - trigger: ":gP:"
      replace: "Π"
      
    # :gp: ⇒ π
    - trigger: ":gp:"
      replace: "π"
      
    # :pi: ⇒ π
    - trigger: ":pi:"
      replace: "π"
      
    # :gQ: ⇒ Χ
    - trigger: ":gQ:"
      replace: "Χ"
      
    # :gq: ⇒ χ
    - trigger: ":gq:"
      replace: "χ"
      
    # :gR: ⇒ Ρ
    - trigger: ":gR:"
      replace: "Ρ"
    
    # :gr: ⇒ ρ
    - trigger: ":gr:"
      replace: "ρ"
      
    # :rho: ⇒ ρ
    - trigger: ":rho:"
      replace: "ρ"
    
    # :gS: ⇒ Σ
    - trigger: ":gS:"
      replace: "Σ"
    
    # :gs: ⇒ σ
    - trigger: ":gs:"
      replace: "σ"
      
    # :gT: ⇒ Τ
    - trigger: ":gT:"
      replace: "Τ"
    
    # :gt: ⇒ τ
    - trigger: ":gt:"
      replace: "τ"
    
    # :gU: ⇒ Υ
    - trigger: ":gU:"
      replace: "Υ"
      
    # :gu: ⇒ υ
    - trigger: ":gu:"
      replace: "υ"
      
    # :gW: ⇒ Ω
    - trigger: ":gW:"
      replace: "Ω"
      
    # :gw: ⇒ ω
    - trigger: ":gw:"
      replace: "ω"
    
    # :gX: ⇒ Ξ
    - trigger: ":gX:"
      replace: "Ξ"
      
    # :gx: ⇒ ξ
    - trigger: ":gx:"
      replace: "ξ"
      
    # :gY: ⇒ Ψ
    - trigger: ":gY:"
      replace: "Ψ"
      
    # :gy: ⇒ ψ
    - trigger: ":gy:"
      replace: "ψ"

    # :gZ: ⇒ Ζ
    - trigger: ":gZ:"
      replace: "Ζ"

    # :gz: ⇒ ζ
    - trigger: ":gz:"
      replace: "ζ"

    
    ## Full name
    # :Alpha: ⇒ Α
    - trigger: ":Alpha:"
      replace: "Α"

    # :alpha: ⇒ α
    - trigger: ":alpha:"
      replace: "α"

    # :Beta: ⇒ Β
    - trigger: ":Beta:"
      replace: "Β"

    # :beta: ⇒ β
    - trigger: ":beta:"
      replace: "β"

    # :Delta: ⇒ Δ
    - trigger: ":Delta:"
      replace: "Δ"

    # :delta: ⇒ δ
    - trigger: ":delta:"
      replace: "δ"

    # :Epsilon: ⇒ Ε
    - trigger: ":Epsilon:"
      replace: "Ε"

    # :epsilon: ⇒ ε
    - trigger: ":epsilon:"
      replace: "ε"

    # :Phi: ⇒ Φ
    - trigger: ":Phi:"
      replace: "Φ"

    # :phi: ⇒ φ
    - trigger: ":phi:"
      replace: "φ"

    # :Gamma: ⇒ Γ
    - trigger: ":Gamma:"
      replace: "Γ"

    # :gamma: ⇒ γ
    - trigger: ":gamma:"
      replace: "γ"

    # :Eta: ⇒ Η
    - trigger: ":Eta:"
      replace: "Η"

    # :eta: ⇒ η
    - trigger: ":eta:"
      replace: "η"

    # :Iota: ⇒ Ι
    - trigger: ":Iota:"
      replace: "Ι"

    # :iota: ⇒ ι
    - trigger: ":iota:"
      replace: "ι"

    # :Theta: ⇒ Θ
    - trigger: ":Theta:"
      replace: "Θ"

    # :theta: ⇒ θ
    - trigger: ":theta:"
      replace: "θ"

    # :Kappa: ⇒ Κ
    - trigger: ":Kappa:"
      replace: "Κ"

    # :kappa: ⇒ κ
    - trigger: ":kappa:"
      replace: "κ"

    # :Lambda: ⇒ Λ
    - trigger: ":Lambda:"
      replace: "Λ"

    # :lambda: ⇒ λ
    - trigger: ":lambda:"
      replace: "λ"

    # :Mu: ⇒ Μ
    - trigger: ":Mu:"
      replace: "Μ"

    # :mu: ⇒ μ
    - trigger: ":mu:"
      replace: "μ"

    # :Nu: ⇒ Ν
    - trigger: ":Nu:"
      replace: "Ν"

    # :nu: ⇒ ν
    - trigger: ":nu:"
      replace: "ν"

    # :Omnicron: ⇒ Ο
    - trigger: ":Omicron:"
      replace: "Ο"

    # :omnicron: ⇒ ο
    - trigger: ":omicron:"
      replace: "ο"

    # :Pi: ⇒ Π
    - trigger: ":Pi:"
      replace: "Π"

    # :pi: ⇒ π
    - trigger: ":pi:"
      replace: "π"

    # :Chi: ⇒ Χ
    - trigger: ":Chi:"
      replace: "Χ"

    # :chi: ⇒ χ
    - trigger: ":chi:"
      replace: "χ"

    # :Rho: ⇒ Ρ
    - trigger: ":Rho:"
      replace: "Ρ"

    # :rho: ⇒ ρ
    - trigger: ":rho:"
      replace: "ρ"

    # :Sigma: ⇒ Σ
    - trigger: ":Sigma:"
      replace: "Σ"

    # :sigma: ⇒ σ
    - trigger: ":sigma:"
      replace: "σ"

    # :Tau: ⇒ Τ
    - trigger: ":Tau:"
      replace: "Τ"

    # :tau: ⇒ τ
    - trigger: ":tau:"
      replace: "τ"

    # :Upsilon: ⇒ Υ
    - trigger: ":Upsilon:"
      replace: "Υ"

    # :upsilon: ⇒ υ
    - trigger: ":upsilon:"
      replace: "υ"

    # :Omega: ⇒ Ω
    - trigger: ":Omega:"
      replace: "Ω"

    # :omega: ⇒ ω
    - trigger: ":omega:"
      replace: "ω"

    # :Xi: ⇒ Ξ
    - trigger: ":Xi:"
      replace: "Ξ"

    # :xi: ⇒ ξ
    - trigger: ":xi:"
      replace: "ξ"

    # :Psi: ⇒ Ψ
    - trigger: ":Psi:"
      replace: "Ψ"

    # :psi: ⇒ ψ
    - trigger: ":psi:"
      replace: "ψ"

    # :Zeta: ⇒ Ζ
    - trigger: ":Zeta:"
      replace: "Ζ"

    # :zeta: ⇒ ζ
    - trigger: ":zeta:"
      replace: "ζ"
