# Math

name: Math Symbols
parent: default

matches:
  # Boolean operaitons
  - trigger: ":and"
    replace: "∧"

  - trigger: ":or"
    replace: "∨"
 
  - trigger: ":xor"
    replace: "⩛"
 

  # Propositions
  - trigger: ":not"
    replace: "¬"

  - triggers: [":impl", ":==>"]
    replace: "⇒"

  - triggers: [":equiv", ":<=>"]
    replace: "⇔"
  

  # Sets
  - trigger: ":forall"
    replace: "∀"

  - trigger: ":exist"
    replace: "∃"

  - trigger: ":inset"
    replace: "∈"
      
  - trigger: ":notin"
    replace: "∉"

  - trigger: ":niset"
    replace: "∋"

  - trigger: ":notni"
    replace: "∌"

  - trigger: ":subset"
    replace: "⊂"

  - trigger: ":subseq"
    replace: "⊆"

  - trigger: ":supset"
    replace: "⊃"

  - trigger: ":supseq"
    replace: "⊇"

  - trigger: ":union"
    replace: "∪"

  - trigger: ":intersect"
    replace: "∩"


  # Comparisons
  - triggers: [":neq", ":!="]
    replace: "≠"

  - triggers: [":leq", ":<="]
    replace: "≤"

  - triggers: [":geq", ":>="]
    replace: "≥"

  - triggers: [":gg", ":>>"]
    replace: "≫"

  - triggers: [":ll", ":<<"]
    replace: "≪"

  - trigger: ":cong"
    replace: "≡"

  - triggers: [":approx", ":~="]
    replace: "≈"


  # Proofs
  - trigger: ":therefore"
    replace: "∴"

  - trigger: ":because"
    replace: "∵"

  - triggers: [":qed", ":kstn", ":box"]
    replace: "■"


  # Misc
  - trigger: ":sqrt"
    replace: "√"

  - trigger: ":check"
    replace: "✓"

  - trigger: ":sum"
    replace: "∑"

  - trigger: ":integral"
    replace: "∫"

  - trigger: ":dagger"
    replace: "†"

  - trigger: ":infty"
    replace: "∞"

  - trigger: ":pm"
    replace: "±"

  - triggers: [":bolt", ":lightning"]
    replace: "↯"

  # Arrows
  - triggers: [":uparrow", ":|^"]
    replace: "↑"

  - triggers: [":downarrow", ":|v"]
    replace: "↓"

  - triggers: [":leftarrow", ":<-"]
    replace: "←"

  - triggers: [":rightarrow", ":->"]
    replace: "→"

  - triggers: [":rsquig", ":~>"]
    replace: "⇝"

  - triggers: [":lsquig", ":<~"]
    replace: "⇜"

  - triggers: [":mapsto", ":|->"]
    replace: "↦"

  # CompSci stuff
  - trigger: ":[[:"
    replace: "⟦"

  - trigger: ":]]:"
    replace: "⟧"

